services:
  cropscout:
    build: .
    container_name: cropscout-interface
    restart: unless-stopped
    ports:
      - '80:8000'
    volumes:
      - ./data:/data
    environment:
      - DATABASE_URL=sqlite:///data/cropscout.db
      - SECRET_KEY=your-secret-key-change-in-production
      - SSL_KEY_FILE=/app/keychain/privkey.pem
      - SSL_CERT_FILE=/app/keychain/fullchain.pem
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:443/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s