services:
  traefik:
    image: traefik:v3.3
    command:
      - '--api.insecure=true'
      - '--providers.docker'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'
      - '--entrypoints.web.http.redirections.entrypoint.to=websecure'
      - '--entrypoints.web.http.redirections.entrypoint.scheme=https'
      - '--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web'
      - '--certificatesresolvers.myresolver.acme.email=kgleba@yandex.ru'
      - '--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json'
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt
    restart: always

  cropscout:
    build: .
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.cropscout.rule=Host(`demo.cropscout.farm`)'
      - 'traefik.http.routers.cropscout.entrypoints=websecure'
      - 'traefik.http.routers.cropscout.tls=true'
      - 'traefik.http.routers.cropscout.tls.certresolver=myresolver'
      - 'traefik.http.services.cropscout.loadbalancer.server.port=8000'
    environment:
      - DATABASE_URL=sqlite:///data/cropscout.db
      - SECRET_KEY=your-secret-key-change-in-production
    volumes:
      - ./cropscout-data:/data
    restart: unless-stopped